// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHE39uyi1-lGDpEpEgJFm5_Dj6cT0prSI',
    appId: '1:1037500155802:web:2013c35dc7041b10cd9c23',
    messagingSenderId: '1037500155802',
    projectId: 'stokado-f375f',
    authDomain: 'stokado-f375f.firebaseapp.com',
    storageBucket: 'stokado-f375f.firebasestorage.app',
    measurementId: 'G-HE1T4W75X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqRtKlYHyUIWqFof88IyDOmfq3J8LxeL0',
    appId: '1:1037500155802:android:c0a4a72ce72c49aacd9c23',
    messagingSenderId: '1037500155802',
    projectId: 'stokado-f375f',
    storageBucket: 'stokado-f375f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_kz_bTjCH8OPIEVQlNXZ5RXhBwt0FrCY',
    appId: '1:1037500155802:ios:14f31fb24345f997cd9c23',
    messagingSenderId: '1037500155802',
    projectId: 'stokado-f375f',
    storageBucket: 'stokado-f375f.firebasestorage.app',
    iosBundleId: 'com.example.sampleFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHE39uyi1-lGDpEpEgJFm5_Dj6cT0prSI',
    appId: '1:1037500155802:web:4ba6d434222785bccd9c23',
    messagingSenderId: '1037500155802',
    projectId: 'stokado-f375f',
    authDomain: 'stokado-f375f.firebaseapp.com',
    storageBucket: 'stokado-f375f.firebasestorage.app',
    measurementId: 'G-X0G5EJ40CZ',
  );
}
